"""initial schema

Revision ID: 0630a852629d
Revises: 
Create Date: 2026-03-04 13:49:31.000906
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0630a852629d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('field_schema', postgresql.JSON(astext_type=sa.Text()), nullable=False, comment='JSON schema defining form fields, labels, regions, and types'),
    sa.Column('sample_image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ENCODER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False, comment='Action type: create, update, delete, verify, login, etc.'),
    sa.Column('entity_type', sa.String(length=50), nullable=False, comment='Entity type: form_entry, user, form_template, etc.'),
    sa.Column('entity_id', sa.String(length=255), nullable=True, comment='ID of the affected entity'),
    sa.Column('changes', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='JSON diff of changes made'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Client IP address'),
    sa.Column('description', sa.Text(), nullable=True, comment='Human-readable description'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('form_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'EXTRACTED', 'VERIFIED', 'ARCHIVED', name='formentrystatus'), nullable=False),
    sa.Column('raw_ocr_data', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Raw OCR extraction output'),
    sa.Column('verified_data', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Human-verified final data'),
    sa.Column('confidence_score', sa.Float(), nullable=True, comment='Overall confidence 0.0-1.0'),
    sa.Column('processing_time', sa.Float(), nullable=True, comment='OCR processing time in seconds'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['form_templates.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_entries_status'), 'form_entries', ['status'], unique=False)
    op.create_index(op.f('ix_form_entries_template_id'), 'form_entries', ['template_id'], unique=False)
    op.create_index(op.f('ix_form_entries_uploaded_by'), 'form_entries', ['uploaded_by'], unique=False)
    op.create_table('form_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False, comment='Field label from template schema'),
    sa.Column('ocr_value', sa.Text(), nullable=True, comment='Raw OCR-extracted value'),
    sa.Column('verified_value', sa.Text(), nullable=True, comment='Human-verified final value'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='Confidence score 0.0-1.0'),
    sa.Column('was_corrected', sa.Boolean(), nullable=False, comment='True if encoder modified the OCR value'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['form_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_fields_entry_id'), 'form_fields', ['entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_fields_entry_id'), table_name='form_fields')
    op.drop_table('form_fields')
    op.drop_index(op.f('ix_form_entries_uploaded_by'), table_name='form_entries')
    op.drop_index(op.f('ix_form_entries_template_id'), table_name='form_entries')
    op.drop_index(op.f('ix_form_entries_status'), table_name='form_entries')
    op.drop_table('form_entries')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('form_templates')
    # ### end Alembic commands ###
